name: fingerfunke_app
description: A new Flutter project.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 
  
  # firebase
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  cloud_functions: ^4.1.1
  firebase_messaging: ^14.4.1

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  bloc: ^8.0.1
  freezed: ^2.1.0
  freezed_annotation: ^2.1.0
  equatable: ^2.0.3
  logger: ^1.1.0
  pin_code_fields: ^7.3.0
  rxdart: ^0.27.2
  google_fonts: ^4.0.4
  uuid: ^3.0.5
  flutter_cache_manager: ^3.1.3
  video_player: ^2.2.7
  intl: ^0.18.0
  dio: ^5.1.2
  mime: ^1.0.1
  path_provider: ^2.0.7
  video_thumbnail: ^0.5.3
  camera: ^0.10.5
  shared_preferences: ^2.0.9
  url_launcher: ^6.0.17
  modal_bottom_sheet: ^3.0.0-pre
  image_cropper: ^4.0.1
  image_picker: ^0.8.6 
  share_plus: ^7.0.0
  auto_size_text: ^3.0.0
  flutter_settings_ui: ^2.0.1
  flutter_feather_icons: ^2.0.0+1
  intl_phone_field: ^3.1.0
  get_storage: ^2.0.3
  google_maps_flutter: ^2.2.6
  google_maps_place_picker_mb: ^3.0.2
  shimmer: ^3.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  package_info_plus: ^4.0.0
  flutter_image_compress: ^2.0.3
  app_settings: ^4.1.8
  tuple: ^2.0.1
  easy_debounce: ^2.0.2+1
  provider: ^6.0.5
  get_it: ^7.2.0
  firebase_ui_firestore: ^1.5.1
  firebase_storage: ^11.2.1
  file_picker: ^5.3.1
  cached_network_image: ^3.2.3
  flutter_pdfview: ^1.3.1
  path: ^1.8.3
  device_info_plus: ^9.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.0.0
  flutter_oss_licenses: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  test: ^1.22.0
  json_serializable: ^6.6.2

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path_android: 'assets/img/brand/icon.png'
  image_path_ios: 'assets/img/brand/fingerfunke_logo_full.png'
  remove_alpha_ios: True

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/img/images/
    - assets/img/placeholder/
    - assets/img/illustrations/
    - assets/img/illustrations/undraw/
    - assets/img/brand/
    - assets/img/partners/
    - assets/vid/
