version: 2.1
orbs:
  flutter: circleci/flutter@2.0.2
  android: circleci/android@2.3.0


jobs:
  deploy-to-testflight:
    macos:
      xcode: "14.2.0"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b2:6f:07:01:53:11:92:f0:fa:1f:39:34:4f:8b:c5:5e"

      - checkout
      
      - run:
          name: Checkout Config File Repo
          command: git clone git@gitlab.com:fingerfunke/config-files.git
          working_directory: ~/
      - run:
          name: Checkout Tools File Repo
          command: git clone git@gitlab.com:fingerfunke/tools.git
          working_directory: ~/
      
      - run:
          name: Create release notes
          # check if circle tag is available, if yes use tools to build release notes
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              echo "CIRCLE_TAG is set to $CIRCLE_TAG"
              echo "Creating release notes"
              python ../tools/get_release_notes_from_changelog.py CHANGELOG.md
            else
              echo "CIRCLE_TAG is not set"
            fi
    

      - flutter/install_sdk_and_pub:
          version: 3.10.1
      - flutter/install_ios_pod
      - flutter/install_ios_gem

      - run:
          name: Config Fastlane (Setup Signing, ...)
          command: bundle exec fastlane prepare
          working_directory: ios
      
      - run:
          name: Config Other Environment Values (Android & iOS)
          command: ./setup_environment.sh
          working_directory: .circleci/scripts

      - run:
          name: Beta Release iOS (Testflight)
          command: bundle exec fastlane beta_testflight
          working_directory: ios
           
      - store_artifacts:
          path: ./ios/Podfile.lock
          destination: cache-ios/Podfile.lock
      
      - store_artifacts:
          path: ./ios/Gemfile.lock
          destination: cache-ios/Gemfile.lock
        
      - store_artifacts:
          path: ./pubspec.lock
          destination: cache-ios/pubspec.lock

  deploy-firebase-distribution-android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.04.1

    steps:
      - add_ssh_keys:
          fingerprints:
            - "b2:6f:07:01:53:11:92:f0:fa:1f:39:34:4f:8b:c5:5e"

      - checkout
      - run:
          name: Checkout Config File Repo
          command: git clone git@gitlab.com:fingerfunke/config-files.git
          working_directory: ~/
      - run:
          name: Checkout Tools File Repo
          command: git clone git@gitlab.com:fingerfunke/tools.git
          working_directory: ~/

      - run:
          name: Create release notes
          # check if circle tag is available, if yes use tools to build release notes
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              echo "CIRCLE_TAG is set to $CIRCLE_TAG"
              echo "Creating release notes"
              python ../tools/get_release_notes_from_changelog.py CHANGELOG.md
            else
              echo "CIRCLE_TAG is not set"
            fi

      - flutter/install_sdk_and_pub:
          version: 3.7.12
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem

      - run:
          name: Config Fastlane (Setup Signing, ...)
          command: bundle exec fastlane prepare
          working_directory: android
      
      - run:
          name: Config Other Environment Values (Android & iOS)
          command: ./setup_environment.sh
          working_directory: .circleci/scripts

      - run:
          name: Beta Release Android (Firebase App Distribution)
          command: bundle exec fastlane beta_firebase_distribution
          working_directory: android
     
      - store_artifacts:
          path: ./pubspec.lock
          destination: cache-android/pubspec.lock
      


workflows:
  deploy-beta:
    jobs:
      - deploy-to-testflight
      - deploy-firebase-distribution-android

    filters:
      tags:
        only: /^v.*/
      branches:
        ignore: /.*/
