# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Set initial configuration"
  lane :prepare do
    # get current build number from testflight
    latest_testflight_build_number = latest_testflight_build_number
    # set build number to latest testflight build number + 1
    ENV["FLUTTER_BUILD_NUMBER"] = latest_testflight_build_number + 1
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
    
    build_app(
      #skip_build_archive: true,
      #archive_path: "../build/ios/archive/Runner.xcarchive",
      #export_team_id: "USQLR37M94",
    )

    upload_to_testflight
  end
end
